version: "3.3"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8001:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - ./vols/mysql/:/var/lib/mysql/
  adminer:
    image: adminer:latest
    restart: always
    environment: 
      ADMINER_DEFAULT_SERVER: mysql
    ports: 
      - 8002:8080
