version: "3.9"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8001:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build: 
      context: .
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./env/mysql.env
    volumes:
      - /var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - "8002:80"
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8003:8025
